# conf/config.yaml
defaults:
  - model: transformer
  - plora
  - data
  - _self_

seed: 42
wandb_logger: true
run_notes: ""
model_name_or_path: "meta-llama/Llama-2-7b-hf"
model_checkpoint: "/careAIDrive/"
input_type: "seq"
debug: true
test: true
trainer:
  batch_size: 64
  lr: 5e-6
  max_epochs: 1
  save_top_k: 1
  devices: "auto"